build: explicitly link the threads library
Otherwise, we get errors like the following when building the project on systems that do not have the pthreads library integrated directly into libc.so, as Bionic does:

ld.bfd: CMakeFiles/termux-elf-cleaner.dir/elf-cleaner.cpp.o: undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'
ld.bfd: /usr/lib/libpthread.so.0: error adding symbols: DSO missing from command line

Merges #36